[package]
name = "proxygit-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "proxygit-server"
path = "src/main.rs"

[dependencies]
proxygit-common = { path = "../proxygit-common" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
hex.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
rusqlite.workspace = true
quinn.workspace = true
quinn-proto.workspace = true
rustls.workspace = true
rcgen.workspace = true
socket2.workspace = true
uuid.workspace = true
tar.workspace = true
flate2.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
proxygit-client = { path = "../proxygit-client" }
